apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: guacd
spec:
  selector:
    matchLabels:
      run: guacd
  replicas: 1
  template:
    metadata:
      labels:
        run: guacd
    spec:
      containers:
      - name: guacd
        image: linuxserver/guacd:1.4.0
        ports:
        - containerPort: 4822
