apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guacamole

generatorOptions:
  disableNameSuffixHash: true

resources:
- 01-guacamole-ns.yaml
- 02-guacamole-svc.yaml
- 04-guacamole-cfm.yaml
- 05-guacamole-dpl.yaml
- ingress.yaml

