apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

generatorOptions:
  disableNameSuffixHash: true

resources:
- account.yaml
- role.yaml
- rolebind.yaml
- service.yaml
