apiVersion: v1
kind: ConfigMap
metadata:
  name: tunnel-zt
  namespace: cloudflare
  labels:
    tunnel: api-zt
data:
  config.yaml: |
    tunnel: <tunnel-id>
    credentials-file: /opt/zt/creds/creds.json
    metrics: 0.0.0.0:8081
    ingress:
    - hostname: guacamole.rainclab.net
      service: http://traefik.kube-system
    - service: http_status:404